spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/campus_swap
    username: postgres
    password: Angel0215evelyn
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080